cmake_minimum_required(VERSION 3.10)
project(MisisTask)

# Задания первой недели
add_executable(w1_1 week_01/0004a.cpp)
add_executable(w1_2 week_01/0271a.cpp)
add_executable(w1_3 week_01/0617a.cpp)

# Задания второй недели
add_executable(w2_1 week_02/0263a.cpp)
add_executable(w2_2 week_02/0978a.cpp)